# -*- coding: utf-8 -*-
"""Model comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmKNDJsLLk560T6eKtZ8dxAaDzZqEeSD
"""

# ==============================
# INSTALLS
# ==============================
!pip install stable-baselines3 gymnasium --quiet

# ==============================
# IMPORTS
# ==============================
import numpy as np
import random
import matplotlib.pyplot as plt
import gymnasium as gym
from gymnasium import spaces

from stable_baselines3 import DQN as SB_DQN
from stable_baselines3 import PPO

# ==============================
# ENVIRONMENT (Gym-compatible)
# ==============================
class SnakeEnvGym(gym.Env):
    def __init__(self, size=9, obstacle_count=0, max_steps=200):
        super().__init__()
        self.size = size
        self.obstacle_count = obstacle_count
        self.max_steps = max_steps

        self.action_space = spaces.Discrete(3)
        self.observation_space = spaces.Box(low=0, high=1, shape=(11,), dtype=np.float32)

    def reset(self, seed=None, options=None):
        self.snake = [(self.size//2, self.size//2)]
        self.direction = (0, 1)
        self.steps = 0

        self.generate_obstacles()
        self.spawn_food()

        return self.get_state(), {}

    def generate_obstacles(self):
        self.obstacles = []
        used = set()

        for _ in range(self.obstacle_count):
            while True:
                x = random.randint(0, self.size-1)
                y = random.randint(0, self.size-1)
                if (x,y) not in used:
                    self.obstacles.append((x,y))
                    used.add((x,y))
                    break

    def spawn_food(self):
        while True:
            self.food = (random.randint(0,self.size-1),
                         random.randint(0,self.size-1))
            if self.food not in self.snake and self.food not in self.obstacles:
                break

    def is_collision(self, point):
        return (
            point in self.snake or
            point in self.obstacles or
            not (0 <= point[0] < self.size) or
            not (0 <= point[1] < self.size)
        )

    def get_state(self):
        head = self.snake[0]

        dir_up = self.direction == (-1,0)
        dir_down = self.direction == (1,0)
        dir_left = self.direction == (0,-1)
        dir_right = self.direction == (0,1)

        left = (head[0], head[1]-1)
        right = (head[0], head[1]+1)
        up = (head[0]-1, head[1])
        down = (head[0]+1, head[1])

        state = [
            self.is_collision(right),
            self.is_collision(left),
            self.is_collision(up),

            self.food[1] < head[1],
            self.food[1] > head[1],
            self.food[0] < head[0],
            self.food[0] > head[0],

            dir_up, dir_down, dir_left, dir_right
        ]

        return np.array(state, dtype=np.float32)

    def step(self, action):
        self.steps += 1

        directions = [(-1,0),(0,1),(1,0),(0,-1)]
        idx = directions.index(self.direction)

        if action == 1:
            idx = (idx+1)%4
        elif action == 2:
            idx = (idx-1)%4

        self.direction = directions[idx]

        head = self.snake[0]
        new_head = (head[0]+self.direction[0],
                    head[1]+self.direction[1])

        if self.is_collision(new_head):
            return self.get_state(), -10, True, False, {}

        self.snake.insert(0, new_head)

        old_dist = abs(head[0]-self.food[0]) + abs(head[1]-self.food[1])
        new_dist = abs(new_head[0]-self.food[0]) + abs(new_head[1]-self.food[1])

        reward = (old_dist - new_dist) - 0.05  # step penalty

        ate_food = False
        if new_head == self.food:
            reward += 10
            self.spawn_food()
            ate_food = True
        else:
            self.snake.pop()

        done = self.steps >= self.max_steps

        return self.get_state(), reward, done, False, {"ate_food": ate_food}

# ==============================
# EVALUATION FUNCTION
# ==============================
def evaluate(agent, env, episodes=50):
    scores = []

    for _ in range(episodes):
        state, _ = env.reset()
        done = False
        food = 0
        steps = 0

        while not done:
            if agent == "random":
                action = env.action_space.sample()
            else:
                action, _ = agent.predict(state, deterministic=True)

            state, _, done, _, info = env.step(action)

            if info.get("ate_food", False):
                food += 1
            steps += 1

        score = food / (steps + 1e-6)
        scores.append(score)

    return np.mean(scores)

# ==============================
# TRAINING
# ==============================
train_env = SnakeEnvGym(9, obstacle_count=0)

dqn_model = SB_DQN("MlpPolicy", train_env, verbose=0)
ppo_model = PPO("MlpPolicy", train_env, verbose=0)

print("Training DQN...")
dqn_model.learn(total_timesteps=20000)

print("Training PPO...")
ppo_model.learn(total_timesteps=20000)

# ==============================
# VALIDATION (detect overfitting)
# ==============================
val_env = SnakeEnvGym(9, obstacle_count=2)

print("\nVALIDATION PERFORMANCE")
print("DQN:", evaluate(dqn_model, val_env))
print("PPO:", evaluate(ppo_model, val_env))
print("Random:", evaluate("random", val_env))

# ==============================
# GENERALIZATION: GRID SIZE
# ==============================
sizes = range(6, 13)

dqn_scores = []
ppo_scores = []
rand_scores = []

for s in sizes:
    env = SnakeEnvGym(s, obstacle_count=0)

    dqn_scores.append(evaluate(dqn_model, env))
    ppo_scores.append(evaluate(ppo_model, env))
    rand_scores.append(evaluate("random", env))

plt.plot(sizes, dqn_scores, label="DQN")
plt.plot(sizes, ppo_scores, label="PPO")
plt.plot(sizes, rand_scores, label="Random")
plt.title("Generalization across Grid Size")
plt.xlabel("Grid Size")
plt.ylabel("Food per Step")
plt.legend()
plt.show()

# ==============================
# GENERALIZATION: OBSTACLES
# ==============================
obstacles = range(0, 9)

dqn_obs = []
ppo_obs = []
rand_obs = []

for k in obstacles:
    env = SnakeEnvGym(9, obstacle_count=k)

    dqn_obs.append(evaluate(dqn_model, env))
    ppo_obs.append(evaluate(ppo_model, env))
    rand_obs.append(evaluate("random", env))

plt.plot(obstacles, dqn_obs, label="DQN")
plt.plot(obstacles, ppo_obs, label="PPO")
plt.plot(obstacles, rand_obs, label="Random")
plt.title("Generalization across Obstacles")
plt.xlabel("Obstacle Count")
plt.ylabel("Food per Step")
plt.legend()
plt.show()