# -*- coding: utf-8 -*-
"""Prototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNnty6XAtUv6tL6c5smh8QMI71zmcorS
"""

#imports
import numpy as np
import random
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from collections import deque

#environment and feature space
class SnakeEnv:
    def __init__(self, size=9, obstacle_count=0):
        self.size = size
        self.obstacle_count = obstacle_count
        self.reset()

    def reset(self):
        self.snake = [(self.size//2, self.size//2)]
        self.direction = (0, 1)

        self.generate_obstacles()
        self.spawn_food()

        return self.get_state()

    def generate_obstacles(self):
        self.obstacles = []

        if self.obstacle_count == 0:
            return

        grid_splits = int(np.sqrt(self.obstacle_count))
        step = self.size // (grid_splits + 1)

        used = set()

        for i in range(grid_splits):
            for j in range(grid_splits):
                if len(self.obstacles) >= self.obstacle_count:
                    break

                x = (i+1)*step + random.randint(-1,1)
                y = (j+1)*step + random.randint(-1,1)

                x = max(0, min(self.size-1, x))
                y = max(0, min(self.size-1, y))

                if (x,y) not in used:
                    self.obstacles.append((x,y))
                    used.add((x,y))

    def spawn_food(self):
        while True:
            self.food = (random.randint(0,self.size-1),
                         random.randint(0,self.size-1))
            if self.food not in self.snake and self.food not in self.obstacles:
                break

    def is_collision(self, point):
        return (
            point in self.snake or
            point in self.obstacles or
            not (0 <= point[0] < self.size) or
            not (0 <= point[1] < self.size)
        )

    def get_state(self):
        head = self.snake[0]

        dir_up = self.direction == (-1,0)
        dir_down = self.direction == (1,0)
        dir_left = self.direction == (0,-1)
        dir_right = self.direction == (0,1)

        left = (head[0], head[1]-1)
        right = (head[0], head[1]+1)
        up = (head[0]-1, head[1])
        down = (head[0]+1, head[1])

        state = [
            (dir_right and self.is_collision(right)) or
            (dir_left and self.is_collision(left)) or
            (dir_up and self.is_collision(up)) or
            (dir_down and self.is_collision(down)),

            (dir_up and self.is_collision(right)) or
            (dir_down and self.is_collision(left)) or
            (dir_left and self.is_collision(up)) or
            (dir_right and self.is_collision(down)),

            (dir_down and self.is_collision(right)) or
            (dir_up and self.is_collision(left)) or
            (dir_right and self.is_collision(up)) or
            (dir_left and self.is_collision(down)),

            self.food[1] < head[1],
            self.food[1] > head[1],
            self.food[0] < head[0],
            self.food[0] > head[0],

            dir_up, dir_down, dir_left, dir_right
        ]

        return np.array(state, dtype=int)

    def step(self, action):
        directions = [(-1,0),(0,1),(1,0),(0,-1)]
        idx = directions.index(self.direction)

        if action == 1:
            idx = (idx+1)%4
        elif action == 2:
            idx = (idx-1)%4

        self.direction = directions[idx]

        head = self.snake[0]
        new_head = (head[0]+self.direction[0],
                    head[1]+self.direction[1])

        if self.is_collision(new_head):
            return self.get_state(), -10, True, False

        self.snake.insert(0, new_head)

        old_dist = abs(head[0]-self.food[0]) + abs(head[1]-self.food[1])
        new_dist = abs(new_head[0]-self.food[0]) + abs(new_head[1]-self.food[1])

        reward = (old_dist - new_dist)

        ate_food = False

        if new_head == self.food:
            reward += 10
            self.spawn_food()
            ate_food = True
        else:
            self.snake.pop()

        return self.get_state(), reward, False, ate_food


#model
class DQN(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, output_dim)
        )

    def forward(self, x):
        return self.net(x)


#training on baseline model
env = SnakeEnv(9, obstacle_count=0)

model = DQN(11,3)
target_model = DQN(11,3)
target_model.load_state_dict(model.state_dict())

optimizer = optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.MSELoss()

memory = deque(maxlen=10000)

gamma = 0.9
epsilon = 1.0
epsilon_min = 0.05
epsilon_decay = 0.995
batch_size = 64

rewards_per_episode = []

for episode in range(750):
    state = env.reset()
    total_reward = 0
    done = False

    max_steps = 200
    steps = 0

    while not done and steps < max_steps:
        steps += 1

        state_tensor = torch.FloatTensor(state).unsqueeze(0)

        if random.random() < epsilon:
            action = random.randint(0,2)
        else:
            with torch.no_grad():
                action = torch.argmax(model(state_tensor)).item()

        next_state, reward, done, _ = env.step(action)

        reward -= 0.05  # prevent looping

        memory.append((state, action, reward, next_state, done))

        state = next_state
        total_reward += reward

        if len(memory) >= batch_size and steps % 4 == 0:
            batch = random.sample(memory, batch_size)
            states, actions, rewards, next_states, dones = zip(*batch)

            states = torch.FloatTensor(states)
            actions = torch.LongTensor(actions).unsqueeze(1)
            rewards = torch.FloatTensor(rewards)
            next_states = torch.FloatTensor(next_states)
            dones = torch.FloatTensor(dones)

            current_q = model(states).gather(1, actions).squeeze()

            with torch.no_grad():
                max_next_q = target_model(next_states).max(1)[0]
                target_q = rewards + (1 - dones) * gamma * max_next_q

            loss = loss_fn(current_q, target_q)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    rewards_per_episode.append(total_reward)
    epsilon = max(epsilon_min, epsilon * epsilon_decay)

    if episode % 50 == 0:
        target_model.load_state_dict(model.state_dict())
        print(f"Episode {episode}, Reward: {total_reward:.2f}, Steps: {steps}")


#training plot
plt.figure(figsize=(10,5))
plt.plot(rewards_per_episode)

window = 20
smoothed = np.convolve(rewards_per_episode, np.ones(window)/window, mode='valid')
plt.plot(range(window-1, len(smoothed)+window-1), smoothed)

plt.title("Training Reward")
plt.xlabel("Episode")
plt.ylabel("Reward")
plt.show()


#evaluation
def evaluate_food(model, env, episodes=100):
    scores = []

    for _ in range(episodes):
        state = env.reset()
        done = False
        total_food = 0
        steps = 0
        max_steps = 200

        while not done and steps < max_steps:
            steps += 1

            state_tensor = torch.FloatTensor(state).unsqueeze(0)
            with torch.no_grad():
                action = torch.argmax(model(state_tensor)).item()

            state, reward, done, ate_food = env.step(action)

            if ate_food:
                total_food += 1

        # normalized efficiency
        efficiency = steps / (total_food + 1e-6)

        # normalize by grid size
        normalized_eff = efficiency / env.size

        scores.append(1 / normalized_eff)  # higher = better

    return np.mean(scores)

#testing performance with changes in scale
sizes = list(range(6, 13))
food_results = []

for size in sizes:
    env_test = SnakeEnv(size, obstacle_count=0)
    food = evaluate_food(model, env_test)
    food_results.append(food)

print("\n=== FOOD RESULTS (SCALING) ===")
for s, f in zip(sizes, food_results):
    print(f"{s}x{s} | Food/Step: {f:.4f}")


#checking performance with obstacles
obstacles = list(range(0, 9))
obs_results = []

for k in obstacles:
    vals = []
    for _ in range(3):  # small averaging
        env_test = SnakeEnv(9, obstacle_count=k)
        vals.append(evaluate_food(model, env_test))
    obs_results.append(np.mean(vals))

print("\n=== FOOD RESULTS for 9x9 (OBSTACLES) ===")
for k, f in zip(obstacles, obs_results):
    print(f"Obstacles {k} | Food/Step: {f:.4f}")


#plots
plt.figure(figsize=(10,5))
plt.plot(sizes, food_results, marker='o')
plt.title("Performance vs Grid Size")
plt.xlabel("Grid Size")
plt.ylabel("Food per Step")
plt.show()

plt.figure(figsize=(10,5))
plt.plot(obstacles, obs_results, marker='o')
plt.title("Performance vs Obstacles (9x9)")
plt.xlabel("Obstacle Count")
plt.ylabel("Food per Step")
plt.show()

results = np.zeros((len(sizes), len(obstacles)))

for i, size in enumerate(sizes):
    for j, k in enumerate(obstacles):
        vals = []
        for _ in range(3):
            env_test = SnakeEnv(size, obstacle_count=k)
            vals.append(evaluate_food(model, env_test))
        results[i, j] = np.mean(vals)

plt.figure(figsize=(10,6))
plt.imshow(results, aspect='auto')

plt.colorbar(label="Food per Step")

plt.xticks(range(len(obstacles)), obstacles)
plt.yticks(range(len(sizes)), sizes)

plt.xlabel("Obstacle Count")
plt.ylabel("Grid Size")
plt.title("Performance Heatmap")

plt.show()

#training on 9x9 with k obstacles
k = 4

env = SnakeEnv(9, obstacle_count=k)

model = DQN(11,3)
target_model = DQN(11,3)
target_model.load_state_dict(model.state_dict())

optimizer = optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.MSELoss()

memory = deque(maxlen=10000)

gamma = 0.9
epsilon = 1.0
epsilon_min = 0.05
epsilon_decay = 0.995
batch_size = 64

print(f"\n=== TRAINING: 9x9 with {k} obstacles ===")

for episode in range(750):
    state = env.reset()
    done = False

    steps = 0
    max_steps = 200

    while not done and steps < max_steps:
        steps += 1

        state_tensor = torch.FloatTensor(state).unsqueeze(0)

        if random.random() < epsilon:
            action = random.randint(0,2)
        else:
            with torch.no_grad():
                action = torch.argmax(model(state_tensor)).item()

        next_state, reward, done, _ = env.step(action)

        reward -= 0.05  # keep consistency

        memory.append((state, action, reward, next_state, done))

        state = next_state

        if len(memory) >= batch_size and steps % 4 == 0:
            batch = random.sample(memory, batch_size)
            states, actions, rewards, next_states, dones = zip(*batch)

            states = torch.FloatTensor(states)
            actions = torch.LongTensor(actions).unsqueeze(1)
            rewards = torch.FloatTensor(rewards)
            next_states = torch.FloatTensor(next_states)
            dones = torch.FloatTensor(dones)

            current_q = model(states).gather(1, actions).squeeze()

            with torch.no_grad():
                max_next_q = target_model(next_states).max(1)[0]
                target_q = rewards + (1 - dones) * gamma * max_next_q

            loss = loss_fn(current_q, target_q)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    epsilon = max(epsilon_min, epsilon * epsilon_decay)

    if episode % 50 == 0:
        target_model.load_state_dict(model.state_dict())
        print(f"Episode {episode}, Epsilon: {epsilon:.3f}")


#test

env_train_eval = SnakeEnv(9, obstacle_count=k)

train_food = evaluate_food(model, env_train_eval)

print(f"\n=== TRAIN PERFORMANCE: 9x9 with {k} obstacles ===")
print(f"Food per step: {train_food:.4f}")


env_test = SnakeEnv(12, obstacle_count=k)

food_eff = evaluate_food(model, env_test)

print(f"\n=== TEST: 12x12 with {k} obstacles ===")
print(f"Food per step: {food_eff:.4f}")

#generalisation test
obstacles = list(range(0, 9))
obs_results = []

print("\n=== GENERALIZATION TEST: 9x9 with varying obstacles ===")

for k_test in obstacles:
    vals = []
    for _ in range(5):  # increase averaging for stability
        env_test = SnakeEnv(9, obstacle_count=k_test)
        vals.append(evaluate_food(model, env_test))

    avg_score = np.mean(vals)
    obs_results.append(avg_score)

    print(f"Obstacles {k_test} | Food/Step: {avg_score:.4f}")

plt.figure(figsize=(10,5))
plt.plot(obstacles, obs_results, marker='o')
plt.title(f"Generalization Across Obstacles (Trained on k={k})")
plt.xlabel("Obstacle Count")
plt.ylabel("Food per Step")
plt.show()